using FluentAssertions;
using HNice.Model.Encryption;
using System.Numerics;
using System.Security.Cryptography;
using System.Text;

namespace HNice.Test.Model.Encryption;

// Expected values were generated by running G-Earth's own BobbaCrypto / Base64Encoding (Java + BouncyCastle)
// with the same fixed private keys.
public class TestsForBobbaCrypto
{
    private static readonly BigInteger ClientPrivateKey = BigInteger.Parse("12345678901234567890");
    private static readonly BigInteger ServerPrivateKey = BigInteger.Parse("9876543210987654321");

    private const string ClientPublicKey = "175748986143666707828408355327054383034367397931988317433695107392864173540973732370036541240168911630818850999715672832957811474744307";
    private const string ServerPublicKey = "491752904312704679984862361787240829681073051982218455408250876417576951817080937584012226735030006006607525432187838458753400333098563";

    [Fact]
    public void ShouldComputeTheSamePublicKeysAsGEarth()
    {
        new BobbaCrypto(ClientPrivateKey).PublicKey.Should().Be(ClientPublicKey);
        new BobbaCrypto(ServerPrivateKey).PublicKey.Should().Be(ServerPublicKey);
    }

    [Fact]
    public void ShouldDeriveTheSameKeysAsGEarth()
    {
        var crypto = new BobbaCrypto(ClientPrivateKey);
        crypto.SetRemotePublicKey(ServerPublicKey);

        crypto.HasKeys.Should().BeTrue();
        Convert.ToHexString(crypto.C2sData!.Key).Should().BeEquivalentTo("b7927d4359c86264350ebb2d8d19512c2c77553e26c73dd4253a33f2b03bc3c0");
        Convert.ToHexString(crypto.C2sData.Nonce).Should().BeEquivalentTo("9bfdc58bc426ece54891aaf0");
        Convert.ToHexString(crypto.C2sHeader!.Key).Should().BeEquivalentTo("689240333b4e286e9709c05020ce1da2b59e4290ef960eaa81f154c50b3ee738");
        Convert.ToHexString(crypto.C2sHeader.Nonce).Should().BeEquivalentTo("51ad6388834af1bab093378b");
        Convert.ToHexString(crypto.S2cData!.Key).Should().BeEquivalentTo("b1891b332d016b97a35b20b8a511aca31a17a2985efb795096ba0619924377b2");
        Convert.ToHexString(crypto.S2cData.Nonce).Should().BeEquivalentTo("e86719d7c820f219efa1ede1");
        Convert.ToHexString(crypto.S2cHeader!.Key).Should().BeEquivalentTo("5f14ef02eb3c7b3031c309151713b75decf106a146eb104802ff56e7c8f0c932");
        Convert.ToHexString(crypto.S2cHeader.Nonce).Should().BeEquivalentTo("191f65a5a8ee3efbe7952e68");
    }

    [Fact]
    public void ShouldUseANewNonceForEveryMessageLikeGEarth()
    {
        var crypto = new BobbaCrypto(ClientPrivateKey);
        crypto.SetRemotePublicKey(ServerPublicKey);
        var message = Encoding.Latin1.GetBytes("@Aabc\u0002");

        Convert.ToHexString(BobbaCrypto.ApplyChaCha(message, crypto.C2sData!)).Should().BeEquivalentTo("4acb8219695f");
        Convert.ToHexString(BobbaCrypto.ApplyChaCha(message, crypto.C2sData!)).Should().BeEquivalentTo("d1eeb2196933");
        Convert.ToHexString(BobbaCrypto.ApplyChaCha(message, crypto.C2sData!)).Should().BeEquivalentTo("7fb2098aeadf");
    }

    [Fact]
    public void ShouldEncryptAChunkLikeGEarth()
    {
        var crypto = new BobbaCrypto(ClientPrivateKey);
        crypto.SetRemotePublicKey(ServerPublicKey);

        var chunk = ShockwavePacketModifier.EncryptChunk(Encoding.Latin1.GetBytes("CJhello"), crypto.S2cHeader!, crypto.S2cData!, headerPrefix: 42);

        Encoding.Latin1.GetString(chunk).Should().Be("kYkMZQH7AcvwHovg");
    }

    [Fact]
    public void ShouldAgreeOnTheSameKeysOnBothSides()
    {
        var client = new BobbaCrypto();
        var server = new BobbaCrypto();

        client.SetRemotePublicKey(server.PublicKey);
        server.SetRemotePublicKey(client.PublicKey);

        client.C2sData!.Key.Should().Equal(server.C2sData!.Key);
        client.C2sHeader!.Nonce.Should().Equal(server.C2sHeader!.Nonce);
        client.S2cData!.Key.Should().Equal(server.S2cData!.Key);
        client.S2cHeader!.Key.Should().Equal(server.S2cHeader!.Key);
        client.C2sData.Key.Should().NotEqual(client.S2cData.Key);
    }

    [Fact]
    public void ShouldMatchRfc7539KeyStreamVector()
    {
        // RFC 7539 A.1, test vector #1: all zero key and nonce, block counter 0.
        var output = new byte[64];
        ChaCha20.Xor(new byte[32], new byte[12], 0, new byte[64], output);

        Convert.ToHexString(output).Should().BeEquivalentTo(
            "76b8e0ada0f13d90405d6ae55386bd28bdd219b8a08ded1aa836efcc8b770dc7" +
            "da41597c5157488d7724e03fb8d84a376a43b8f41518a11cc387b669b2ee6586");
    }

    [Theory]
    [InlineData(1)]
    [InlineData(63)]
    [InlineData(64)]
    [InlineData(65)]
    [InlineData(300)]
    public void ShouldMatchTheFrameworkChaCha20(int length)
    {
        if (!ChaCha20Poly1305.IsSupported) return;

        var key = RandomNumberGenerator.GetBytes(32);
        var nonce = RandomNumberGenerator.GetBytes(12);
        var plaintext = RandomNumberGenerator.GetBytes(length);

        // The AEAD construction encrypts with block counter 1.
        var expected = new byte[length];
        using (var aead = new ChaCha20Poly1305(key))
        {
            aead.Encrypt(nonce, plaintext, expected, new byte[16]);
        }

        var actual = new byte[length];
        ChaCha20.Xor(key, nonce, 1, plaintext, actual);

        actual.Should().Equal(expected);
    }

    [Fact]
    public void ShouldEncodeBase64WithoutPaddingLikeGEarth()
    {
        byte[] data = [0, 1, 2, 250, 251, 252, 253];
        Encoding.ASCII.GetString(CipherBase64.Encode(data)).Should().Be("AAEC+vv8/Q");
    }

    [Fact]
    public void ShouldRoundTripBase64ForEveryLength()
    {
        for (var length = 0; length < 20; length++)
        {
            var data = RandomNumberGenerator.GetBytes(length);
            var encoded = CipherBase64.Encode(data);

            Encoding.ASCII.GetString(encoded).Should().Be(Convert.ToBase64String(data).TrimEnd('='));
            CipherBase64.Decode(encoded).Should().Equal(data);
        }
    }
}
